networks:
  nicccce-acm-calendar-net:
    driver: bridge

services:
  app:
    build: ../nicccce-acm-calendar-api
    container_name: nicccce-acm-calendar-api
    volumes:
      - ./config.prod.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - nicccce-acm-calendar-net

  mysql:
    image: mysql:8.0
    container_name: nicccce-acm-calendar-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nicccce-acm-calendar-db
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    privileged: true
    restart: always
    networks:
      - nicccce-acm-calendar-net

  redis:
    image: redis:7.0
    container_name: nicccce-acm-calendar-redis
    command: --requirepass q4jrFTeVVRGOnna3KGWQ
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    privileged: true
    restart: always
    networks:
      - nicccce-acm-calendar-net

  nginx:
    image: nginx:alpine
    container_name: nicccce-acm-calendar-nginx
    ports:
      - "80:80"
    volumes:
      - ../scrip-version:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
    networks:
      - nicccce-acm-calendar-net

#  watchtower:
#    image: containrrr/watchtower
#    container_name: activity-punch-system-backend-watchtower
#    command: --interval 5
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # 需要将 Docker 的 sock 映射进去以控制 Docker
#    restart: always
#    networks:
#      - nicccce-acm-calendar-net