networks:
  nicccce-acm-calendar-net:
    driver: bridge

services:
  nicccce-acm-calendar-api:
    image: nicccce-acm-calendar-api
    container_name: nicccce-acm-calendar-api
    volumes:
      - ./config.prod.yaml:/app/config.yaml
    depends_on:
      nicccce-acm-calendar-db:
        condition: service_healthy
    restart: always
    networks:
      - nicccce-acm-calendar-net

  nicccce-acm-calendar-db:
    image: mysql:8.0
    container_name: nicccce-acm-calendar-db
    environment:
      MYSQL_ROOT_PASSWORD: q4jrFTeVVRGOnna3KGWQ
      MYSQL_DATABASE: nicccce-acm-calendar-db
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    privileged: true
    restart: always
    networks:
      - nicccce-acm-calendar-net

  nicccce-acm-calendar-redis:
    image: redis:7.0
    container_name: nicccce-acm-calendar-redis
    command: --requirepass q4jrFTeVVRGOnna3KGWQ
    environment:
      TZ: Asia/Shanghai
    privileged: true
    restart: always
    networks:
      - nicccce-acm-calendar-net

  nicccce-acm-calendar-frontend:
    image: nicccce-acm-calendar-frontend
    container_name: nicccce-acm-calendar-frontend
    depends_on:
      - nicccce-acm-calendar-api
    restart: always
    ports: 
        - 8030:80
    networks:
      - nicccce-acm-calendar-net

#  watchtower:
#    image: containrrr/watchtower
#    container_name: activity-punch-system-backend-watchtower
#    command: --interval 5
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock # 需要将 Docker 的 sock 映射进去以控制 Docker
#    restart: always
#    networks:
#      - nicccce-acm-calendar-net
